# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Uglify
        run: sudo npm install uglify-js -g
      - name: Install Dependencies
        run: npm install
      - name: Add frongjs
        run: "cat <<< \"<script type=\"text/javascript\">(function (w) {w.frontjsConfig = { token: \"5ba108e63b146e3c744535fabc53b581\", behaviour: 9, captureConsoleLog: true, trustVendor: true, ignoreVendor: true, optimisedForSPA: true, useHistory: true, FPSThreshold: 10 }; w.frontjsTmpData = {r: [], e: [], l: [] }; w.frontjsTmpCollector = function (ev) {(ev.message ? window.frontjsTmpData.e : window.frontjsTmpData.r).push([new Date().getTime(), ev])}; w.FrontJS = {addEventListener: function (t, f) {w.frontjsTmpData.l.push([t, f]); return f; }, removeEventListener: function (t, f) { for (var i = 0; i < w.frontjsTmpData.l.length; i++) {t === w.frontjsTmpData.l[i][0] && f === w.frontjsTmpData.l[i][1] && w.frontjsTmpData.l.splice(i, 1); } return f; } }; w.document.addEventListener(\"error\", w.frontjsTmpCollector, true); w.addEventListener(\"error\", w.frontjsTmpCollector, true); w.addEventListener(\"load\", function () { var n = w.document.createElement(\"script\"); n.src = \"https://frontjs-static.pgyer.com/dist/current/frontjs.web.min.js\"; w.document.body.appendChild(n); }, true); })(window);</script>\" > frontjs"
      - name: Add 360fenxi
        run: cat <<< "<script type=\"text/javascript\">/* 360统计代码 */ (function (b, a, e, h, f, c, g, s) { b[h] = b[h] || function () { (b[h].c = b[h].c || []).push(arguments); }; b[h].s = !!c; g = a.getElementsByTagName(e)[0]; s = a.createElement(e); s.src = \"//s.union.360.cn/\" + f + \".js\"; s.defer = !0; s.async = !0; g.parentNode.insertBefore(s, g); })(window, document, \"script\", \"_qha\", 361707, false); </script>" > 360fenxi
      - name: Add bdtongji
        run: cat <<< "<script type=\"text/javascript\">/* 百度统计代码 */ var _hmt = _hmt || []; (function () { var hm = document.createElement(\"script\"); hm.src = \"https://hm.baidu.com/hm.js?dd18823003a9883d07ac0b24b75f9d16\"; var s = document.getElementsByTagName(\"script\")[0]; s.parentNode.insertBefore(hm, s); })(); </script>" > bdtongji
      - name: Set permission
        run: chmod +x ./publish.sh
      - name: Devlop dependencies
        run: ./publish.sh build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
